import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD'
});

function downloadBlob(filename, mimeType, content) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function exportScheduleCsv(label, schedule) {
  const rows = [
    ['Month', 'Payment', 'Principal', 'Interest', 'Remaining Balance'],
    ...schedule.map((row) => [row.month, row.payment, row.principal, row.interest, row.balance])
  ];
  const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n');
  downloadBlob(`${label}-amortization.csv`, 'text/csv;charset=utf-8', csv);
}

export function exportSchedulePdf(label, schedule) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text(`${label} Amortization Schedule`, 14, 20);
  doc.setFontSize(10);
  doc.text('Generated by LoanIQ Pro. Review with a licensed financial professional before making lending decisions.', 14, 28);

  autoTable(doc, {
    startY: 36,
    head: [['Month', 'Payment', 'Principal', 'Interest', 'Balance']],
    body: schedule.map((row) => [
      row.month,
      currencyFormatter.format(row.payment),
      currencyFormatter.format(row.principal),
      currencyFormatter.format(row.interest),
      currencyFormatter.format(row.balance)
    ]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [16, 42, 67] }
  });

  doc.save(`${label}-amortization.pdf`);
}
